application: beunscripted-1295
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: .*
  script: main.app

- url: /partials
  static_dir: static/partials

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
